In [ ]:
# Imports 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import yfinance as yf
import csv
import matplotlib.dates as mdates 
import seaborn as sns
from scipy.stats import norm, gmean, cauchy
import sktime
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
from sklearn.metrics import mean_absolute_error, mean_squared_error
from arch import arch_model
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import acf
from scipy.linalg import solve
from scipy import stats
from scipy.optimize import minimize, rosen, rosen_der
from scipy.stats import probplot
from statsmodels.stats.diagnostic import het_arch
from numba import jit
import os
import timeit

print("Imports complete!")

Imports complete!

In [13]:
os.getcwd()

'/Users/amadika'

In [ ]:
def PreProcessing():
  principal_df = pd.read_csv("/Users/amadika/Documents/GitHub/microfin/index and stat arb/SPTop50.csv")
  return principal_df

principal_df = PreProcessing()

In [ ]:
principal_df.head()

,Price,Close,Close.1,Close.2,Close.3,Close.4,Close.5,Close.6,Close.7,Close.8,...,Volume.40,Volume.41,Volume.42,Volume.43,Volume.44,Volume.45,Volume.46,Volume.47,Volume.48,Volume.49
0,Ticker,AAPL,ABBV,ABT,ACN,AMZN,AVGO,AXP,BAC,BRK-B,...,T,TMO,TMUS,TSLA,UNH,V,VZ,WFC,WMT,XOM
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-01-03,9.917946815490723,NaN,16.942659378051758,37.585784912109375,9.211000442504883,1.975299596786499,35.33056640625,11.223381996154785,80.41000366210938,...,27251760,2416400,3619000,19245000,8212400,25710000,20099500,34397100,42894900,23320700
3,2011-01-04,9.969707489013672,NaN,17.102096557617188,37.338253021240234,9.250499725341797,1.9895100593566895,35.778289794921875,11.26292896270752,80.16999816894531,...,27522253,3109100,9442250,17811000,6724300,18138000,22668600,30341100,36463200,20028500
4,2011-01-05,10.051260948181152,NaN,17.102096557617188,37.345985412597656,9.371000289916992,1.9887995719909668,36.81642150878906,11.468568801879883,80.91000366210938,...,37266893,2665400,7795100,21700500,7528100,38512800,33918500,43245600,42646800,16550800

In [ ]:
print(*principal_df.columns)
principal_df[''].isnull()

Price Close Close.1 Close.2 Close.3 Close.4 Close.5 Close.6 Close.7 Close.8 Close.9 Close.10 Close.11 Close.12 Close.13 Close.14 Close.15 Close.16 Close.17 Close.18 Close.19 Close.20 Close.21 Close.22 Close.23 Close.24 Close.25 Close.26 Close.27 Close.28 Close.29 Close.30 Close.31 Close.32 Close.33 Close.34 Close.35 Close.36 Close.37 Close.38 Close.39 Close.40 Close.41 Close.42 Close.43 Close.44 Close.45 Close.46 Close.47 Close.48 Close.49 High High.1 High.2 High.3 High.4 High.5 High.6 High.7 High.8 High.9 High.10 High.11 High.12 High.13 High.14 High.15 High.16 High.17 High.18 High.19 High.20 High.21 High.22 High.23 High.24 High.25 High.26 High.27 High.28 High.29 High.30 High.31 High.32 High.33 High.34 High.35 High.36 High.37 High.38 High.39 High.40 High.41 High.42 High.43 High.44 High.45 High.46 High.47 High.48 High.49 Low Low.1 Low.2 Low.3 Low.4 Low.5 Low.6 Low.7 Low.8 Low.9 Low.10 Low.11 Low.12 Low.13 Low.14 Low.15 Low.16 Low.17 Low.18 Low.19 Low.20 Low.21 Low.22 Low.23 Low.24 Low.25 Low.26 Low.27 Low.28 Low.29 Low.30 Low.31 Low.32 Low.33 Low.34 Low.35 Low.36 Low.37 Low.38 Low.39 Low.40 Low.41 Low.42 Low.43 Low.44 Low.45 Low.46 Low.47 Low.48 Low.49 Open Open.1 Open.2 Open.3 Open.4 Open.5 Open.6 Open.7 Open.8 Open.9 Open.10 Open.11 Open.12 Open.13 Open.14 Open.15 Open.16 Open.17 Open.18 Open.19 Open.20 Open.21 Open.22 Open.23 Open.24 Open.25 Open.26 Open.27 Open.28 Open.29 Open.30 Open.31 Open.32 Open.33 Open.34 Open.35 Open.36 Open.37 Open.38 Open.39 Open.40 Open.41 Open.42 Open.43 Open.44 Open.45 Open.46 Open.47 Open.48 Open.49 Volume Volume.1 Volume.2 Volume.3 Volume.4 Volume.5 Volume.6 Volume.7 Volume.8 Volume.9 Volume.10 Volume.11 Volume.12 Volume.13 Volume.14 Volume.15 Volume.16 Volume.17 Volume.18 Volume.19 Volume.20 Volume.21 Volume.22 Volume.23 Volume.24 Volume.25 Volume.26 Volume.27 Volume.28 Volume.29 Volume.30 Volume.31 Volume.32 Volume.33 Volume.34 Volume.35 Volume.36 Volume.37 Volume.38 Volume.39 Volume.40 Volume.41 Volume.42 Volume.43 Volume.44 Volume.45 Volume.46 Volume.47 Volume.48 Volume.49

,Price,Close,Close.1,Close.2,Close.3,Close.4,Close.5,Close.6,Close.7,Close.8,...,Volume.40,Volume.41,Volume.42,Volume.43,Volume.44,Volume.45,Volume.46,Volume.47,Volume.48,Volume.49
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1820,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1821,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1822,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1823,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Processing tools to avoid leakage and look-ahead bias, using numba
def mean_without_lookahead():
  pass

def mean

In [ ]:
# Processing tools without using numba